package org.whsv26.reporter

sealed trait MetricName

case object OrdersQty extends MetricName
case object OrdersInApprovedStatusQty extends MetricName
case object OrdersInApprovedStatusPercent extends MetricName
case object OrdersInSpamStatusQty extends MetricName
case object OrdersInSpamStatusPercent extends MetricName
case object OrdersInCanceledStatusQty extends MetricName
case object OrdersInCanceledStatusPercent extends MetricName
